### ISSUE TITLE
"Suitable Lora" Conversion

### ISSUE THREAD

**Issue by NicholasKao1029** [haofanwang/Lora-for-Diffusers#10]
A "suitable lora" is mentioned in this conversion script https://github.com/haofanwang/Lora-for-Diffusers/blob/18adfa4da0afec46679eb567d5a3690fd6a4ce9c/format_convert.py#L154-L161 

Can you explain what that means?

**Comment by haofanwang** [comment]
Most of LoRA from civitai platform should be fine. As the converting is actually a key mapping process, so if some LoRAs have different naming, it will be problematic. @erjanmx

**Comment by NicholasKao1029** [comment]
kk cool thanks
