### ISSUE TITLE
TypeError: to() received an invalid combination of arguments - got (torch.dtype, NoneType), but expected one of:

### ISSUE THREAD

**Issue by nwangfw** [haofanwang/Lora-for-Diffusers#11]
Hi there,

I got the following error when I tried to use the script provided.

TypeError: to() received an invalid combination of arguments - got (torch.dtype,
NoneType), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy, *, 
torch.memory_format memory_format)
 * (torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format 
memory_format)
 * (Tensor tensor, bool non_blocking, bool copy, *, torch.memory_format 
memory_format)

You can reproduce it with the following Colab link,
https://colab.research.google.com/drive/1BXOY6kjhU4qeRDfAM70GMDaqidqs-Jrg?usp=sharing

Any suggestions will be appreciated!

**Comment by haofanwang** [comment]
Hi @nwangfw 

There is a typo in the code. I have fixed it. Thanks for pointing out!
